defaults:
  - override hydra/launcher: submitit_local

experiment: test
path: ${oc.env:PROCESSED_TRAIN_NO_TL}
num_files: 100
n_cpus: 7
lr: 3e-4
samples_per_epoch: 50000
max_visible_road_points: 500
batch_size: 512
epochs: 700
device: cuda
n_stacked_states: 5
view_dist: 80
view_angle: 3.14
actions_are_positions: False
discrete: True
seed: 0

# WANDB things
wandb: True
wandb_project: nocturne
wandb_group: ${experiment}

# tensorboard logs
write_to_tensorboard: True

results_dir: ${oc.env:NOCTURNE_LOG_DIR}
hydra:
  run:
    dir: ${results_dir}/test/${now:%Y.%m.%d}/${experiment}/${now:%H.%M.%S}/${hydra.job.override_dirname}
  sweep:
    dir: ${results_dir}/${oc.env:USER}/nocturne/sweep/${now:%Y.%m.%d}/${experiment}/${now:%H.%M.%S}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 2880
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ${results_dir}/sweep/${now:%Y.%m.%d}/${now:%H%M}_${experiment}/.slurm
